In [26]:
import pandas as pd

In [27]:
nav_df = pd.read_csv("../data/raw/02_nav_history.csv")

In [38]:
nav_df.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [39]:
nav_df.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [40]:
nav_df["date"] = pd.to_datetime(nav_df["date"])

In [41]:
nav_df = nav_df.sort_values(["amfi_code", "date"])

In [42]:
nav_df["nav"].isnull().sum()

np.int64(0)

In [43]:
nav_df["nav"] = nav_df.groupby("amfi_code")["nav"].ffill()

In [44]:
nav_df = nav_df.drop_duplicates()

In [45]:
print("Number of rows:", len(nav_df))

Number of rows: 46000

In [46]:
print((nav_df["nav"] > 0).all())

True

In [47]:
nav_df.to_csv("../data/processed/nav_history_clean.csv", index=False)

In [48]:
nav_df["nav"].isnull().sum()

np.int64(0)

# Cleaning investor_transactions.csv

In [49]:
txn_df = pd.read_csv("../data/raw/08_investor_transactions.csv")

In [50]:
txn_df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [51]:
txn_df.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [52]:
txn_df["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [53]:
txn_df["transaction_type"] = (
    txn_df["transaction_type"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [54]:
txn_df["transaction_type"].unique()

<StringArray>
['Sip', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [55]:
txn_df["transaction_type"] = txn_df["transaction_type"].replace({
    "Sip": "SIP",
    "Lumpsum": "Lumpsum",
    "Redemption": "Redemption"
})

In [56]:
txn_df["transaction_date"] = pd.to_datetime(txn_df["transaction_date"])

In [57]:
print((txn_df["amount_inr"] > 0).all())

True

In [58]:
txn_df["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [59]:
valid = ["Verified", "Pending"]

print(txn_df["kyc_status"].isin(valid).all())

True

In [60]:
txn_df.to_csv(
    "../data/processed/investor_transactions_clean.csv",
    index=False
)

In [61]:
txn_df["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [62]:
txn_df["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [63]:
print((txn_df["amount_inr"] > 0).all())

True

In [6]:
import os

print(os.getcwd())

c:\Users\madhu\OneDrive\Desktop\MutualFundAnalytics\notebooks

In [10]:
import pandas as pd

scheme_df = pd.read_csv("../data/raw/07_scheme_performance.csv")

scheme_df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [11]:
"../data/raw/07_scheme_performance.csv"

'../data/raw/07_scheme_performance.csv'

In [12]:
scheme_df.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [13]:
scheme_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [14]:
scheme_df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [15]:
return_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct'
]

scheme_df[return_cols].dtypes

return_1yr_pct       float64
return_3yr_pct       float64
return_5yr_pct       float64
benchmark_3yr_pct    float64
dtype: object

In [16]:
invalid_expense = scheme_df[
    (scheme_df['expense_ratio_pct'] < 0.1) |
    (scheme_df['expense_ratio_pct'] > 2.5)
]

invalid_expense

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [17]:
anomalies = scheme_df[
    (scheme_df['return_1yr_pct'] < -100) |
    (scheme_df['return_1yr_pct'] > 100) |
    (scheme_df['return_3yr_pct'] < -100) |
    (scheme_df['return_3yr_pct'] > 100) |
    (scheme_df['return_5yr_pct'] < -100) |
    (scheme_df['return_5yr_pct'] > 100)
]

anomalies

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [18]:
scheme_df.to_csv(
    "../data/processed/scheme_performance_clean.csv",
    index=False
)

print("✅ scheme_performance_clean.csv saved successfully.")

✅ scheme_performance_clean.csv saved successfully.