In [26]:
import pandas as pd

In [27]:
nav_df = pd.read_csv("../data/raw/02_nav_history.csv")

In [38]:
nav_df.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [39]:
nav_df.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [40]:
nav_df["date"] = pd.to_datetime(nav_df["date"])

In [41]:
nav_df = nav_df.sort_values(["amfi_code", "date"])

In [42]:
nav_df["nav"].isnull().sum()

np.int64(0)

In [43]:
nav_df["nav"] = nav_df.groupby("amfi_code")["nav"].ffill()

In [44]:
nav_df = nav_df.drop_duplicates()

In [45]:
print("Number of rows:", len(nav_df))

Number of rows: 46000

In [46]:
print((nav_df["nav"] > 0).all())

True

In [47]:
nav_df.to_csv("../data/processed/nav_history_clean.csv", index=False)

In [48]:
nav_df["nav"].isnull().sum()

np.int64(0)

# Cleaning investor_transactions.csv

In [49]:
txn_df = pd.read_csv("../data/raw/08_investor_transactions.csv")

In [50]:
txn_df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [51]:
txn_df.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [52]:
txn_df["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [53]:
txn_df["transaction_type"] = (
    txn_df["transaction_type"]
    .astype(str)
    .str.strip()
    .str.title()
)

In [54]:
txn_df["transaction_type"].unique()

<StringArray>
['Sip', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [55]:
txn_df["transaction_type"] = txn_df["transaction_type"].replace({
    "Sip": "SIP",
    "Lumpsum": "Lumpsum",
    "Redemption": "Redemption"
})

In [56]:
txn_df["transaction_date"] = pd.to_datetime(txn_df["transaction_date"])

In [57]:
print((txn_df["amount_inr"] > 0).all())

True

In [58]:
txn_df["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [59]:
valid = ["Verified", "Pending"]

print(txn_df["kyc_status"].isin(valid).all())

True

In [60]:
txn_df.to_csv(
    "../data/processed/investor_transactions_clean.csv",
    index=False
)

In [61]:
txn_df["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [62]:
txn_df["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [63]:
print((txn_df["amount_inr"] > 0).all())

True

In [6]:
import os

print(os.getcwd())

c:\Users\madhu\OneDrive\Desktop\MutualFundAnalytics\notebooks

In [10]:
import pandas as pd

scheme_df = pd.read_csv("../data/raw/07_scheme_performance.csv")

scheme_df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [11]:
"../data/raw/07_scheme_performance.csv"

'../data/raw/07_scheme_performance.csv'

In [12]:
scheme_df.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [13]:
scheme_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [14]:
scheme_df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [15]:
return_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct'
]

scheme_df[return_cols].dtypes

return_1yr_pct       float64
return_3yr_pct       float64
return_5yr_pct       float64
benchmark_3yr_pct    float64
dtype: object

In [16]:
invalid_expense = scheme_df[
    (scheme_df['expense_ratio_pct'] < 0.1) |
    (scheme_df['expense_ratio_pct'] > 2.5)
]

invalid_expense

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [17]:
anomalies = scheme_df[
    (scheme_df['return_1yr_pct'] < -100) |
    (scheme_df['return_1yr_pct'] > 100) |
    (scheme_df['return_3yr_pct'] < -100) |
    (scheme_df['return_3yr_pct'] > 100) |
    (scheme_df['return_5yr_pct'] < -100) |
    (scheme_df['return_5yr_pct'] > 100)
]

anomalies

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [18]:
scheme_df.to_csv(
    "../data/processed/scheme_performance_clean.csv",
    index=False
)

print("✅ scheme_performance_clean.csv saved successfully.")

✅ scheme_performance_clean.csv saved successfully.

In [19]:
import pandas as pd
from sqlalchemy import create_engine

In [22]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:Madhu%405155@localhost:5432/bluestock_db"
)

print("connected")

connected

In [23]:
import pandas as pd

pd.read_sql("SELECT 1", engine)

   ?column?
0         1

In [24]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:Madhu%405155@localhost:5432/bluestock_db"
)

pd.read_sql("SELECT 1", engine)

   ?column?
0         1

In [25]:
fund_df = scheme_df[[
    "amfi_code",
    "scheme_name",
    "fund_house",
    "category",
    "plan"
]].drop_duplicates()

fund_df.to_sql("dim_fund", engine, if_exists="append", index=False)

40

In [26]:
pd.read_sql("SELECT * FROM dim_fund LIMIT 5", engine)

,fund_id,amfi_code,scheme_name,fund_house,category,plan
0,1,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular
1,2,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct
2,3,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular
3,4,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct
4,5,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular

In [28]:
aum_df = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")
aum_df.columns

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

In [30]:
nav_df = pd.read_csv("../data/processed/nav_history_clean.csv")

In [31]:
nav_df.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [33]:
txn_df = pd.read_csv("../data/processed/investor_transactions_clean.csv")

In [34]:
nav_df.columns
txn_df.columns
aum_df.columns

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

In [35]:
txn_df.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [37]:
# Convert all date columns to datetime
nav_df["date"] = pd.to_datetime(nav_df["date"])
txn_df["transaction_date"] = pd.to_datetime(txn_df["transaction_date"])
aum_df["date"] = pd.to_datetime(aum_df["date"])

# Collect all unique dates
all_dates = pd.concat([
    nav_df["date"],
    txn_df["transaction_date"],
    aum_df["date"]
]).drop_duplicates().sort_values()

# Create Date Dimension
dim_date = pd

In [39]:
type(dim_date)

module

In [40]:
type(dim_date)

module

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "postgresql://postgres:Madhu%405155@localhost:5432/bluestock_db"
)

In [3]:
pd.read_sql("SELECT 1;", engine)

   ?column?
0         1

In [4]:
scheme_df = pd.read_csv("../data/processed/scheme_performance_clean.csv")

nav_df = pd.read_csv("../data/processed/nav_history_clean.csv")

txn_df = pd.read_csv("../data/processed/investor_transactions_clean.csv")

aum_df = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")

In [5]:
nav_df["date"] = pd.to_datetime(nav_df["date"])
txn_df["transaction_date"] = pd.to_datetime(txn_df["transaction_date"])
aum_df["date"] = pd.to_datetime(aum_df["date"])

all_dates = pd.concat([
    nav_df["date"],
    txn_df["transaction_date"],
    aum_df["date"]
]).drop_duplicates().sort_values()

dim_date = pd.DataFrame({"full_date": all_dates})

dim_date["day"] = dim_date["full_date"].dt.day
dim_date["month"] = dim_date["full_date"].dt.month
dim_date["year"] = dim_date["full_date"].dt.year
dim_date["quarter"] = dim_date["full_date"].dt.quarter

In [6]:
type(dim_date)

pandas.DataFrame

In [7]:
dim_date.to_sql(
    "dim_date",
    con=engine,
    if_exists="append",
    index=False
)

print("✅ dim_date loaded successfully")

✅ dim_date loaded successfully

In [8]:
pd.read_sql("SELECT * FROM dim_date LIMIT 10;", engine)

   date_id   full_date  day  month  year  quarter
0        1  2022-01-03    3      1  2022        1
1        2  2022-01-04    4      1  2022        1
2        3  2022-01-05    5      1  2022        1
3        4  2022-01-06    6      1  2022        1
4        5  2022-01-07    7      1  2022        1
5        6  2022-01-10   10      1  2022        1
6        7  2022-01-11   11      1  2022        1
7        8  2022-01-12   12      1  2022        1
8        9  2022-01-13   13      1  2022        1
9       10  2022-01-14   14      1  2022        1

In [9]:
fund_dim = pd.read_sql("""
SELECT fund_id, amfi_code
FROM dim_fund
""", engine)

date_dim = pd.read_sql("""
SELECT date_id, full_date
FROM dim_date
""", engine)

In [10]:
nav_df["date"] = pd.to_datetime(nav_df["date"])
date_dim["full_date"] = pd.to_datetime(date_dim["full_date"])

In [11]:
fact_nav = nav_df.merge(
    fund_dim,
    on="amfi_code",
    how="left"
)

In [12]:
fact_nav = fact_nav.merge(
    date_dim,
    left_on="date",
    right_on="full_date",
    how="left"
)

In [13]:
fact_nav = fact_nav[[
    "fund_id",
    "date_id",
    "nav"
]]

fact_nav.rename(
    columns={"nav": "nav_value"},
    inplace=True
)

fact_nav.head()

   fund_id  date_id  nav_value
0        6        1   520.4608
1        6        2   515.0971
2        6        3   521.7239
3        6        4   515.7880
4        6        5   515.1639

In [14]:
fact_nav.to_sql(
    "fact_nav",
    con=engine,
    if_exists="append",
    index=False
)

print("✅ fact_nav loaded successfully")

✅ fact_nav loaded successfully

In [15]:
pd.read_sql(
    "SELECT * FROM fact_nav LIMIT 10;",
    engine
)

   nav_id  fund_id  date_id  nav_value
0       1        6        1   520.4608
1       2        6        2   515.0971
2       3        6        3   521.7239
3       4        6        4   515.7880
4       5        6        5   515.1639
5       6        6        6   510.7136
6       7        6        7   513.5542
7       8        6        8   512.3195
8       9        6        9   510.2445
9      10        6       10   514.3636

In [16]:
fund_dim = pd.read_sql("""
SELECT fund_id, amfi_code
FROM dim_fund
""", engine)

fund_dim.head()

   fund_id  amfi_code
0        1     119551
1        2     119552
2        3     119598
3        4     119599
4        5     119120

In [17]:
fact_performance = scheme_df.merge(
    fund_dim,
    on="amfi_code",
    how="left"
)

In [18]:
fact_performance = fact_performance[[
    "fund_id",
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct",
    "benchmark_3yr_pct",
    "alpha",
    "beta",
    "sharpe_ratio",
    "sortino_ratio",
    "std_dev_ann_pct",
    "max_drawdown_pct",
    "expense_ratio_pct",
    "morningstar_rating",
    "risk_grade"
]]

In [19]:
fact_performance.to_sql(
    "fact_performance",
    con=engine,
    if_exists="append",
    index=False
)

print("✅ fact_performance loaded")

✅ fact_performance loaded

In [20]:
print(nav_df.shape)
print(txn_df.shape)

(46000, 3)
(32778, 13)

In [21]:
scheme_df.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [22]:
fund_dim = pd.read_sql("""
SELECT fund_id, amfi_code
FROM dim_fund
""", engine)

In [23]:
fact_performance = scheme_df.merge(
    fund_dim,
    on="amfi_code",
    how="left"
)

In [24]:
fact_performance = fact_performance[[
    "fund_id",
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct",
    "benchmark_3yr_pct",
    "alpha",
    "beta",
    "sharpe_ratio",
    "sortino_ratio",
    "std_dev_ann_pct",
    "max_drawdown_pct",
    "expense_ratio_pct",
    "morningstar_rating",
    "risk_grade"
]]

In [25]:
fact_performance.to_sql(
    "fact_performance",
    engine,
    if_exists="append",
    index=False
)

print("✅ fact_performance loaded")

✅ fact_performance loaded

In [26]:
fact_performance.to_sql(
    "fact_performance",
    engine,
    if_exists="append",
    index=False
)

40

In [2]:
import pandas as pd

In [3]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///bluestock.db")

In [6]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", engine)

Empty DataFrame
Columns: [name]
Index: []

In [7]:
engine

Engine(sqlite:///bluestock.db)

In [8]:
print(engine.url)

sqlite:///bluestock.db

In [9]:
import os

print(os.getcwd())

c:\Users\madhu\OneDrive\Desktop\MutualFundAnalytics\notebooks

In [10]:
engine = create_engine("sqlite:///bluestock.db")

In [11]:
import os

print(os.path.exists("../bluestock.db"))
print(os.path.exists("bluestock.db"))

False
True

In [12]:
import os

print(os.path.abspath("../bluestock.db"))
print(os.path.abspath("bluestock.db"))

c:\Users\madhu\OneDrive\Desktop\MutualFundAnalytics\bluestock.db
c:\Users\madhu\OneDrive\Desktop\MutualFundAnalytics\notebooks\bluestock.db

In [13]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", engine)

Empty DataFrame
Columns: [name]
Index: []

In [14]:
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../bluestock.db")

In [15]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", engine)

Empty DataFrame
Columns: [name]
Index: []

In [16]:
import os

print("Root DB:")
print(os.path.getsize("../bluestock.db"))

print("Notebook DB:")
print(os.path.getsize("bluestock.db"))

Root DB:
0
Notebook DB:
0

In [17]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith(".db"):
            print(os.path.join(root, file))

..\bluestock.db
..\notebooks\bluestock.db

In [18]:
print(engine.url)

sqlite:///../bluestock.db

In [19]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://username:password@localhost:5432/database_name"
)

In [21]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:Madhu%405155@localhost:5432/bluestock_db"
)

In [22]:
pd.read_sql("SELECT version();", engine)

                                             version
0  PostgreSQL 18.4 on x86_64-windows, compiled by...

In [23]:
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
""", engine)

          table_name
0           dim_date
1           dim_fund
2           fact_aum
3           fact_nav
4   fact_performance
5  fact_transactions

In [24]:
pd.read_sql("""
SELECT COUNT(*) AS total_rows
FROM fact_performance;
""", engine)

   total_rows
0          40

In [25]:
tables = [
    "dim_fund",
    "dim_date",
    "fact_nav",
    "fact_transactions",
    "fact_performance",
    "fact_aum"
]

for table in tables:
    count = pd.read_sql(f"SELECT COUNT(*) AS count FROM {table};", engine)
    print(f"{table}:")
    print(count)
    print("-" * 30)

dim_fund:
   count
0     40
------------------------------
dim_date:
   count
0   1297
------------------------------
fact_nav:
   count
0  46000
------------------------------
fact_transactions:
   count
0      0
------------------------------
fact_performance:
   count
0     40
------------------------------
fact_aum:
   count
0      0
------------------------------

In [29]:
pd.read_sql("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'fact_nav';
""", engine)

  column_name
0      nav_id
1     fund_id
2     date_id
3   nav_value

# SQL Analysis Queries

In [42]:
query1 = """
SELECT
    f.scheme_name,
    a.aum_crore
FROM fact_aum a
JOIN dim_fund f
ON a.fund_id = f.fund_id
ORDER BY a.aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query1, engine)

Empty DataFrame
Columns: [scheme_name, aum_crore]
Index: []

In [43]:
query2 = """
SELECT
    d.year,
    d.month,
    ROUND(AVG(n.nav_value), 2) AS avg_nav
FROM fact_nav n
JOIN dim_date d
ON n.date_id = d.date_id
GROUP BY d.year, d.month
ORDER BY d.year, d.month;
"""

pd.read_sql(query2, engine)

    year  month  avg_nav
0   2022      1   207.06
1   2022      2   207.72
2   2022      3   209.69
3   2022      4   211.83
4   2022      5   212.73
5   2022      6   213.86
6   2022      7   213.96
7   2022      8   215.68
8   2022      9   218.49
9   2022     10   219.53
10  2022     11   223.47
11  2022     12   226.76
12  2023      1   230.67
13  2023      2   233.85
14  2023      3   238.01
15  2023      4   240.61
16  2023      5   241.89
17  2023      6   244.61
18  2023      7   245.78
19  2023      8   247.73
20  2023      9   251.83
21  2023     10   255.61
22  2023     11   258.35
23  2023     12   262.02
24  2024      1   264.62
25  2024      2   266.33
26  2024      3   269.60
27  2024      4   271.30
28  2024      5   273.45
29  2024      6   275.47
30  2024      7   279.02
31  2024      8   279.74
32  2024      9   281.02
33  2024     10   282.13
34  2024     11   285.24
35  2024     12   285.27
36  2025      1   288.04
37  2025      2   291.74
38  2025      3   296.16
39  2025      4   299.41
40  2025      5   303.94
41  2025      6   306.88
42  2025      7   309.73
43  2025      8   313.18
44  2025      9   316.13
45  2025     10   321.45
46  2025     11   325.68
47  2025     12   331.73
48  2026      1   337.12
49  2026      2   342.08
50  2026      3   347.19
51  2026      4   355.03
52  2026      5   357.04

In [44]:
pd.read_sql("SELECT * FROM fact_performance LIMIT 5;", engine)

,performance_id,fund_id,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,expense_ratio_pct,morningstar_rating,risk_grade
0,81,1,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,1.54,4,Moderate
1,82,2,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,0.66,3,Moderate
2,83,3,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,1.43,5,Very High
3,84,4,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,0.72,4,Very High
4,85,5,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,0.77,5,Low

In [45]:
pd.read_sql("SELECT * FROM fact_aum LIMIT 5;", engine)

Empty DataFrame
Columns: [aum_id, fund_id, date_id, aum_crore]
Index: []

In [46]:
query3 = """
SELECT
    df.scheme_name,
    fa.aum_crore
FROM fact_aum fa
JOIN dim_fund df
ON fa.fund_id = df.fund_id
ORDER BY fa.aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query3, engine)

Empty DataFrame
Columns: [scheme_name, aum_crore]
Index: []

In [47]:
query4 = """
SELECT
    df.scheme_name,
    fp.return_5yr_pct
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
ORDER BY fp.return_5yr_pct DESC
LIMIT 5;
"""

pd.read_sql(query4, engine)

                                      scheme_name  return_5yr_pct
0          ABSL Small Cap Fund - Regular - Growth           23.80
1          Axis Small Cap Fund - Regular - Growth           22.62
2  Nippon India Small Cap Fund - Regular - Growth           21.88
3       SBI Small Cap Fund - Direct Plan - Growth           21.82
4      SBI Small Cap Fund - Regular Plan - Growth           20.67

In [48]:
query5 = """
SELECT
    df.category,
    ROUND(AVG(fp.expense_ratio_pct),2) AS avg_expense
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id=df.fund_id
GROUP BY df.category
ORDER BY avg_expense;
"""

pd.read_sql(query5, engine)

           category  avg_expense
0    Short Duration         0.56
1              Gilt         0.66
2            Liquid         0.71
3         Index/ETF         0.89
4         Large Cap         1.26
5         Small Cap         1.35
6           Mid Cap         1.37
7             Value         1.41
8   Large & Mid Cap         1.52
9         Flexi Cap         1.55
10            Index         1.57
11             ELSS         1.60

In [49]:
query6 = """
SELECT
    df.scheme_name,
    fp.sharpe_ratio
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id=df.fund_id
ORDER BY fp.sharpe_ratio DESC
LIMIT 5;
"""

pd.read_sql(query6, engine)

                                    scheme_name  sharpe_ratio
0      ICICI Pru Liquid Fund - Regular - Growth          7.68
1          Kotak Liquid Fund - Regular - Growth          6.18
2           ABSL Liquid Fund - Regular - Growth          5.14
3  HDFC Short Term Debt Fund - Regular - Growth          1.84
4  SBI Magnum Gilt Fund - Regular Plan - Growth          1.52

In [50]:
query7 = """
SELECT
    df.scheme_name,
    fp.expense_ratio_pct
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id=df.fund_id
ORDER BY fp.expense_ratio_pct
LIMIT 5;
"""

pd.read_sql(query7, engine)

                                         scheme_name  expense_ratio_pct
0  Nippon India Gilt Securities Fund - Regular - ...               0.55
1       HDFC Short Term Debt Fund - Regular - Growth               0.56
2               Kotak Liquid Fund - Regular - Growth               0.60
3           SBI Bluechip Fund - Direct Plan - Growth               0.66
4          SBI Small Cap Fund - Direct Plan - Growth               0.72

In [51]:
query8 = """
SELECT
    df.scheme_name,
    fp.alpha
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
ORDER BY fp.alpha DESC
LIMIT 5;
"""

pd.read_sql(query8, engine)

                                     scheme_name  alpha
0   HDFC Short Term Debt Fund - Regular - Growth   1.98
1  Kotak Emerging Equity Fund - Regular - Growth   1.91
2       ICICI Pru Liquid Fund - Regular - Growth   1.85
3         Kotak Flexicap Fund - Regular - Growth   1.85
4         ABSL Small Cap Fund - Regular - Growth   1.84

In [52]:
query9 = """
SELECT
    df.scheme_name,
    fp.max_drawdown_pct
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
ORDER BY fp.max_drawdown_pct DESC
LIMIT 5;
"""

pd.read_sql(query9, engine)

                                         scheme_name  max_drawdown_pct
0  Nippon India Gilt Securities Fund - Regular - ...             -2.23
1       SBI Magnum Gilt Fund - Regular Plan - Growth             -2.30
2           ICICI Pru Liquid Fund - Regular - Growth             -2.62
3                ABSL Liquid Fund - Regular - Growth             -3.66
4               Kotak Liquid Fund - Regular - Growth             -3.81

In [53]:
query10 = """
SELECT
    df.category,
    ROUND(AVG(fp.return_5yr_pct),2) AS avg_return
FROM fact_performance fp
JOIN dim_fund df
ON fp.fund_id = df.fund_id
GROUP BY df.category
ORDER BY avg_return DESC;
"""

pd.read_sql(query10, engine)

           category  avg_return
0         Small Cap       21.90
1           Mid Cap       17.52
2   Large & Mid Cap       15.68
3         Flexi Cap       14.64
4              ELSS       14.26
5         Large Cap       13.32
6             Value       12.60
7         Index/ETF       12.31
8             Index       11.31
9            Liquid        8.05
10             Gilt        7.07
11   Short Duration        6.41